config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/clients'
    get 'admin/users'
    get 'users/profile'
    get 'acc/:id/edit', to: 'admin_company_contacts#edit', as: "edit_acc"
    patch 'acc/:id', to: 'admin_company_contacts#update'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'
  delete "u/:id", to: 'users#destroy'
  get '/user' => "clients#index", :as => :user_root

  #created to filter clients in the table
  resources :clients do
    collection do
      get 'list'
    end
  end

  #send emails to clients
  get 'clients/:id/send_welcome', to: 'clients#welcome'
  get 'quotes/:id/send_quote', to: 'quotes#send_quote'

  #pages roots with quotes
  root 'pages#index'
  get '/stats', to: 'pages#stats'
  get 'quote', to: "pages#quote"
  get 'download', to: "pages#download"
  get 'preview', to: "pages#preview"
  get 'quote/pdf/:id', to: "quotes#pdf", as: 'quote_pdf'

end

app/models/quote.rb
class Quote < ApplicationRecord
	has_secure_token :invoice_number
	enum quote_type: {
    Maestria_Digital_Premium: 11999,
    Maestria_Digital_Elite: 19900
	}
	enum status: {
		Disabled: 0,
		Active: 1
	}
	belongs_to :client
	validates :quote_type, presence: true
	validates :status, presence: true
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy pdf send_quote]
  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new(quote_params)
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def pdf
    @acc = AdminCompanyContact.first
    pdf = ExportPdf.new(@quote, @acc)
    send_data pdf.render,
      filename: "#{@quote.client.company}_sb_quote.pdf",
      type: 'application/pdf',
      disposition: 'inline'
    
  end

  def send_quote
    @client = @quote.client
    UserMailer.with(quote: @quote, client: @client).send_quote.deliver_later
    flash[:notice] = "Quote sent to client via email"
    redirect_to @client
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.fetch(:quote, {}).permit(:quote_type, :amount, :client_id, :extra_amount, :status)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-controller="form-element">

    <%= form.button "Refresh", formaction: new_quote_path, formmethod: :get, data: { turbo_frame: :total_amount,form_element_target: "submitbtn" } %>

    <div>
      <%= form.label :quote_type, class: "form-label", style: "display: block" %>
      <%= form.select :quote_type, Quote.quote_types.keys.map{ |key| [key.humanize, key] }, {include_blank: true, class: "form-select"},{ data: { action: "change->form-element#remotesubmit" }}%>
    </div>

    <div class="mt-2">
      <%= form.label :client_id , class: "form-label", style: "display: block" %>
      <%= form.collection_select :client_id, Client.all, :id, :company, class: "form-select", :prompt => "Select the client" %>
    </div>

    <div class="col-4 mt-2">
      <%= form.label :status, "Status", class: "form-label", style: "display: block" %>
      <%= form.select :status, Quote.statuses.keys ,class: "form-select", prompt: "Select quote status" %>
    </div>

    <div class="col-4 mt-2">
      <%= form.label :extra_amount, "Extra Amount", class: "form-label", style: "display: block" %>
      <%= form.number_field :extra_amount, data: { action: "change->form-element#remotesubmit" }, class: "form-control" %>
    </div>




  
  <% quote.amount = quote.extra_amount.to_i + Quote.quote_types[quote.quote_type].to_i %>
 
  </div>

    <%= turbo_frame_tag :total_amount do %>
      <div class="mt-2">
        Amount for service: <%= quote.amount %> MXN
      </div>
      <div>
        <%= form.hidden_field :amount, value: quote.amount %>
      </div>
    <% end %>

    <div class="mt-3">
      <%= form.submit class: "btn btn-outline-secondary" %>
    </div>
<% end %>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">
  <p>
    <strong>Type:</strong>
    <%= quote.quote_type.humanize %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= quote.status %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= number_to_currency(quote.amount, precision: 0) %>
  </p>

  <p>
    <strong>Client id:</strong>
    <%= quote.client_id %>
    <strong>Client Name:</strong>
    <%= quote.client.company %>
  </p>

  <p>
    <strong>Invoice Number:</strong>
    <%= quote.invoice_number %>
  </p>

</div>

<%= link_to "View PDF", quote_pdf_path(quote), class: "btn btn-outline-primary" %>

app/views/quotes/edit.html.erb
<div class="container">
  <h1>Editing quote</h1>

  <%= render "form", quote: @quote %>

  <br>

  <div>
    <%= link_to "Show this quote", @quote, class: "btn btn-outline-success" %>
    <%= link_to "Back to quotes", quotes_path, class: "btn btn-outline-info" %>
  </div>
</div>

app/views/quotes/index.html.erb
<div class="container">
  <h1>Quotes</h1>
  <%= link_to "New quote", new_quote_path, class: "btn btn-success" %>

  <div class="table-responsive-md mt-3">
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr class="table-secondary">
          <th scope="col">Company</th>
          <th scope="col">Quote Type</th>
          <th scope="col">Package Amount</th>
          <th scope="col">Extra Amount</th>
          <th scope="col">Total amount</th>
          <th scope="col">Created At</th>
          <th scope="col">View PDF</th>
          <th scope="col" colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <% @quotes.each do |quote| %>
          <tr scope="row" class="table-light">
            <td><%= quote.client.company %></td>
            <td><%= quote.quote_type.humanize %></td>
            <td><%= number_to_currency(Quote.quote_types[quote.quote_type], precision: 0) %></td>
            <td><%= number_to_currency(quote.extra_amount, precision: 0) %></td>
            <td><%= number_to_currency(quote.amount, precision: 0) %></td>
            <td><%= quote.created_at.to_date %></td>
            <td><%= link_to "View PDF", quote_pdf_path(quote) %></td>
            <td class="text-center"><%= link_to "Show", quote_path(quote), :class => "btn btn-secondary" %></td>
            <td class="text-center"><%= link_to "Edit", edit_quote_path(quote), :class => "btn btn-secondary" %></td>
            <td class="text-center"><%= link_to "Delete", quote_path(quote), :class => "btn btn-danger" ,data: { "turbo_method": :delete, "turbo_confirm": "Are you sure?"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/quotes/new.html.erb
<div class="container">
  <h1>New quote</h1>

  <%= render "form", quote: @quote %>

  <br>

  <div>
    <%= link_to "Back to quotes", quotes_path, class: "btn btn-outline-warning" %>
  </div>
</div>

app/views/quotes/show.html.erb
<div class="container">
  <h1>Showing Quote</h1>

  <%= render @quote %>

  <div class="mt-3">
    <%= link_to "Edit this quote", edit_quote_path(@quote), class: "btn btn-outline-secondary" %>
    <%= link_to "Back to quotes", quotes_path, class: "btn btn-outline-info" %>
    <%= link_to "Destroy this quote", @quote, method: :delete, class: "btn btn-outline-danger" %>
  </div>
</div>