config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/clients'
    get 'admin/users'
    get 'users/profile'
    get 'acc/:id/edit', to: 'admin_company_contacts#edit', as: "edit_acc"
    patch 'acc/:id', to: 'admin_company_contacts#update'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'
  delete "u/:id", to: 'users#destroy'
  get '/user' => "clients#index", :as => :user_root

  #created to filter clients in the table
  resources :clients do
    collection do
      get 'list'
    end
  end

  #send emails to clients
  get 'clients/:id/send_welcome', to: 'clients#welcome'
  get 'quotes/:id/send_quote', to: 'quotes#send_quote'

  #pages roots with quotes
  root 'pages#index'
  get '/stats', to: 'pages#stats'
  get 'quote', to: "pages#quote"
  get 'download', to: "pages#download"
  get 'preview', to: "pages#preview"
  get 'quote/pdf/:id', to: "quotes#pdf", as: 'quote_pdf'

end

app/views/admin/clients.html.erb
<h1>Admin#clients</h1>
<p>Find me in app/views/admin/clients.html.erb</p>

app/views/admin/index.html.erb
<div class="ms-3">

	<h1 class="mb-3">Admin Home</h1>

	<%= link_to "CRM Users", admin_users_path, class: "btn btn-outline-primary" %>
	
	<h3 class="mt-3">Company Contact Info</h3>
	<%= turbo_frame_tag @acc do %>
		<%= render 'layouts/messages' %>

		<div>Email: <%= @acc.email %> </div>
		<div>Phone: <%= @acc.phone %> </div>
		<%= link_to "Edit Company Contact", edit_acc_path(@acc), class: "btn btn-outline-success mt-3" %>
	<% end %>
</div>

app/views/admin/users.html.erb
<h1 class="m-3">Users List</h1>

<div class="ms-3">
	<%= link_to "Admin Home", admin_path, class: "btn btn-outline-secondary" %>

	<%= link_to "Create new user", admin_users_path, :class => "btn btn-primary m-3" %>
</div>

<div class="table-responsive-md m-3">
	<table class="table table-striped table-hover table-bordered">
		<thead>
			<tr class="table-secondary">
				<th scope="col">First Name</th>
				<th scope="col">Last Name</th>
				<th scope="col">Email</th>
				<th scope="col">Role</th>
				<th scope="col">Created At</th>
				<th scope="col" colspan="2">Actions</th>
			</tr>
		</thead>
		<tbody class="table-group-divider">
			<% @users.each do |user| %>
				<tr scope="row" class="table-light">
					<td><%= user.first_name %></td>
					<td><%= user.last_name %></td>
					<td><%= user.email %></td>
					<td><%= user.role %></td>
					<td><%= user.created_at.to_date %></td>
					<td class="text-center"><%= link_to "Delete", user_path(user), :class => "btn btn-danger" ,data: { "turbo_method": :delete, "turbo_confirm": "Are you sure?"} %></td>


				</tr>
			<% end %>
		</tbody>
	</table>
</div>