config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/clients'
    get 'admin/users'
    get 'users/profile'
    get 'acc/:id/edit', to: 'admin_company_contacts#edit', as: "edit_acc"
    patch 'acc/:id', to: 'admin_company_contacts#update'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'
  delete "u/:id", to: 'users#destroy'
  get '/user' => "clients#index", :as => :user_root

  #created to filter clients in the table
  resources :clients do
    collection do
      get 'list'
    end
  end

  #send emails to clients
  get 'clients/:id/send_welcome', to: 'clients#welcome'
  get 'quotes/:id/send_quote', to: 'quotes#send_quote'

  #pages roots with quotes
  root 'pages#index'
  get '/stats', to: 'pages#stats'
  get 'quote', to: "pages#quote"
  get 'download', to: "pages#download"
  get 'preview', to: "pages#preview"
  get 'quote/pdf/:id', to: "quotes#pdf", as: 'quote_pdf'

end

app/models/client.rb
class Client < ApplicationRecord
	enum status: {
		prospect: 10,
		client: 20,
		renew: 30,
		cancelled: 40,
		vip: 50
	}
	belongs_to :user
	has_many :quotes
	validates :first_name, presence: true, length: {minimum: 3, maximum: 100}
	validates :last_name, presence: true, length: {minimum: 3, maximum: 100}
	validates :company, presence: true, length: {minimum: 1, maximum: 100}
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :set_client, only: [:show, :edit, :update, :destroy, :welcome]

	def index
		@clients = Client.all.order(created_at: :desc)
	end

	def show
	end

	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		@client.user = current_user
		if @client.save
			flash[:notice] = "Client was successfully saved"
			redirect_to @client
		else 
			render 'new', status: :unprocessable_entity
		end
	end

	def edit
	end

	def update
		if @client.update(client_params)
			flash[:notice] = "Client was successfully updated"
			redirect_to @client
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@client.destroy
		flash[:notice] = "Client was successfully deleted"
		redirect_to clients_path
	end

	def list
		clients = Client.order("#{params[:column]} #{params[:direction]}")
		render(partial: 'clients', locals: { clients: clients})
	end

	def welcome
		if @client.email.present?
			UserMailer.with(client: @client).welcome.deliver_later
			flash[:notice] = "Welcome email sent to client"
			redirect_to @client
		else
			flash[:error] = "Please add an email to this client"
			redirect_to @client
		end
	end

	private

	def set_client
		@client = Client.find(params[:id])
	end

	def client_params
		params.require(:client).permit(:first_name, :last_name,
		 :company, :status, :whatsapp, :email, :notes, :phone, :industry,
		 :location, :facebook, :instagram, :linkedin)
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
	def sort_link(column:, label:)
		if column == params[:column]
			link_to(label, list_clients_path(column: column, direction: next_direction))
		else
			link_to(label, list_clients_path(column:column, direction: 'asc'))
		end
	end

	def next_direction
		params[:direction] == 'asc' ? 'desc' : 'asc'
	end

	def sort_indicator
		tag.span(class: "sort sort-#{params[:direction]}")
	end
end

app/views/clients/_clients.html.erb
<%= turbo_frame_tag "clients" do %>
	<div class="table-responsive-md m-3">
		<table class="table table-striped table-hover table-bordered">
			<thead>
				<tr class="table-secondary text-center">
					<th id="clients-first_name" scope="col" class="relative">
						<%= sort_indicator if params[:column] == "first_name" %>
						<%= sort_link(column: "first_name", label: "First Name") %>
					</th>
					<th id="clients-last_name" scope="col" class="relative">
						<%= sort_indicator if params[:column] == "last_name" %>
						<%= sort_link(column: "last_name", label: "Last Name") %>
					</th>
					<th id="clients-company" scope="col" class="relative">
						<%= sort_indicator if params[:column] == "company" %>
						<%= sort_link(column: "company", label: "Company") %>
						
					</th>
					<th id="clients-status" scope="col" class="relative">
						<%= sort_indicator if params[:column] == "status" %>
						<%= sort_link(column: "status", label: "Status") %>
					</th>
					<th scope="col">Whatsapp</th>
					<th scope="col">Email</th>
					<th id="clients-create_at" scope="col" class="relative">
						<%= sort_indicator if params[:column] == "created_at" %>
						<%= sort_link(column: "created_at", label: "Created at") %>
					</th>
					<th id="clients-update_at"scope="col" class="relative">
						<%= sort_indicator if params[:column] == "updated_at" %>
						<%= sort_link(column: "updated_at", label: "Updated at") %>
					</th>
					<th scope="col" colspan="3">Actions</th>
				</tr>
			</thead>
			<tbody class="table-group-divider">
				<% clients.each do |client| %>
					<tr scope="row" class="table-light">
						<td><%= client.first_name %></td>
						<td><%= client.last_name %></td>
						<td><%= client.company %></td>
						<td><%= client.status %></td>
						<td><%= client.whatsapp %>
							<% if client.whatsapp.present? %>
								<%= link_to icon("whatsapp", class: "text-success"),
								"https://api.whatsapp.com/send/?phone=" + client.whatsapp,
								target: '_blank' %>		
							<% end %>
						</td>
						<td><%= client.email %>
							<% if client.email.present? %>
							<%= link_to icon("envelope", class: "contact-icon" ),
							"mailto:" + client.email %>
							<% end %>
						</td>
						<td><%= client.created_at.to_date %></td>
						<td><%= client.updated_at.to_date %></td>
						<td class="text-center"><%= link_to "Show", client_path(client), :class => "btn btn-secondary" %></td>
						<td class="text-center"><%= link_to "Edit", edit_client_path(client), :class => "btn btn-secondary" %></td>
						<td class="text-center"><%= link_to "Delete", client_path(client), :class => "btn btn-danger" ,data: { "turbo_method": :delete, "turbo_confirm": "Are you sure?"} %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
<% end %>

app/views/clients/_form.html.erb
<%= render 'shared/errors' %>

<div>
	<%= form_with(model: @client, local: true) do |f| %>

		<div class="col-4"> 
			<%= f.label :first_name, class: "col-form-label"  %>
			<%= f.text_field :first_name, class: "form-control", placeholder: "First Name of Client" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :last_name, class: "form-label" %>
			<%= f.text_field :last_name, class: "form-control", placeholder: "Last Name of Client" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :company, class: "form-label" %>
			<%= f.text_field :company, class: "form-control", placeholder: "Name of Client Company"%>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :industry, class: "form-label" %>
			<%= f.text_field :industry, class: "form-control", placeholder: "Industry Type" %>
		</div>

		<div class="col-4 mt-2"> 
			<%= f.label :location, class: "form-label" %>
			<%= f.text_field :location, class: "form-control", placeholder: "Location" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :status, class: "form-label" %>
			<div class="form-group">
			<%= f.select :status, Client.statuses.keys.to_a, class: "form-select", include_blank: true %>
			</div>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :phone, class: "form-label" %>
			<%= f.text_field :phone, class: "form-control", placeholder: "Phone number"%>			
		</div>

		<div class="col-4 mt-2">
			<%= f.label :whatsapp, class: "form-label" %>
			<%= f.text_field :whatsapp, class: "form-control", placeholder: "Whatsapp"%>			
		</div>

		<div class="col-4 mt-2">
			<%= f.label :email, class: "form-label" %>
			<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :facebook, class: "form-label" %>
			<%= f.text_field :facebook, class: "form-control", placeholder: "Facebook" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :instagram, class: "form-label" %>
			<%= f.text_field :instagram, class: "form-control", placeholder: "Instagram" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :linkedin, class: "form-label" %>
			<%= f.text_field :linkedin, class: "form-control", placeholder: "Linkedin" %>
		</div>

		<div class="col-4 mt-2">
			<%= f.label :notes, class: "form-label" %>
			<%= f.text_area :notes, class: "form-control", placeholder: "Notes" %>
			
		</div>

		<div class="mt-4 mb-2"> <%= f.submit class: "btn btn-outline-primary" %> </div>

	<% end %>
	<div class="mb-2">
		<%= link_to "Cancel and return to clients home", clients_path, class: "btn btn-outline-success"%>
	</div>

</div>

app/views/clients/edit.html.erb
<div class="m-2">
	<h1>Update the client</h1>
		
	<%= render 'form' %>

	<%= link_to "Delete Client", client_path(@client), data: { "turbo_method": :delete, "turbo-confirm": "Are you sure?"}, class: "btn btn-outline-danger" %>
</div>

app/views/clients/index.html.erb
<%= stylesheet_link_tag "example", "data-turbo-track": "reload" %>

<h1 class="ms-3">Clients List</h1>

<div>
	<%= link_to "Create new client", new_client_path, :class => "btn btn-primary ms-3" %>
</div>

<%= render 'clients', clients: @clients %>

app/views/clients/new.html.erb
<div class="m-2">
	<h1>Create a new client</h1>
		
		
	<%= render 'form' %>

</div>

app/views/clients/show.html.erb
<div class="d-flex flex-column h-100">

	<!-- Card 1 -->

	<div class="row">
		<div class="card text-bg-light m-3 col-4" style="max-width: 18rem;">
			<div class="card-header">Showing Client</div>
			<div class="card-body">
				<div><b>Client First Name:</b> <%= @client.first_name %></div>
				<div><b>Client Last Name:</b> <%= @client.last_name %></div>
				<div><b>Company:</b> <%= @client.company %> </div>
				<div><b>Industry:</b> <%= @client.industry %> </div>
				<div><b>Location:</b> <%= @client.location %> </div>
				<div><b>Status:</b> <%= @client.status %></div>
				<div><b>Created:</b> <%= time_ago_in_words(@client.created_at) %> ago</div> 
				<div><b>Updated:</b> <%= time_ago_in_words(@client.updated_at) %> ago</div>
				<div><b>Created by:</b> <%= @client.user.first_name %></div>
			</div>
		</div>

		<!-- Card 2 -->

		<div class="card text-bg-light m-3 col-4" style="max-width: 18rem;">
			<div class="card-header">Client Contact Info</div>
			<div class="card-body">
				<div><b>Phone:</b> <%= @client.phone %></div>
				<div><b>Whatsapp:</b>
					<%= @client.whatsapp %>
					<% if @client.whatsapp.present? %>
						<%= link_to icon("whatsapp", class: "text-success"),
						"https://api.whatsapp.com/send/?phone=" + @client.whatsapp,
						target: '_blank' %>
					<% end %>
				</div>
				<div><b>Email: </b>
					<%= @client.email %>
					<% if @client.email.present? %>
						<%= link_to icon("envelope", class: "text-primary" ),
						"mailto:" + @client.email %>
					<% end %>
				</div>
				<div><b>Facebook:</b>
					<% if @client.facebook.present? %> 
						<%= link_to @client.facebook,
						if @client.facebook.include? "http://"
						then @client.facebook else "https://" + @client.facebook end %> 
					<% end %>
				</div>
				<div><b>Instagram:</b>
					<% if @client.instagram.present? %> 
						<%= link_to @client.instagram,
						if @client.instagram.include? "https://" 
						then @client.instagram else "https://" + @client.instagram end %> 
					<% end %>
				</div>
				<div><b>LinkedIn:</b>
					<% if @client.linkedin.present? %> 
						<%= link_to @client.linkedin,
						if @client.linkedin.include? "https://" 
						then @client.linkedin else "https://" + @client.linkedin end %>
					<% end %>
				</div>
			</div>
		</div>

		<!-- Card 3 -->

		<div class="card text-bg-light m-3 col-4" style="max-width: 18rem;">
			<div class="card-header">More Client Info</div>
			<div class="card-body">
				<div><b>Notes:</b> <%= @client.notes%></div>
				
			</div>
		</div>
	</div>
		
		<!-- Buttons -->
		<div class="ms-3">
			<div class="my-2">
				<%= link_to "Clients Home", clients_path, class: "btn btn-outline-primary"%>
			</div>
			<div class="my-2">
				<%= link_to "Send Welcome Email", client_path(@client)+'/send_welcome', class: "btn btn-outline-warning" %>
			</div>
			<div class="mb-2">
				<%= link_to "Edit Client", edit_client_path(@client), class: "btn btn-outline-success" %>
			</div>
			<div class="mb-2">
				<%= link_to "Delete Client", client_path(@client), data: { "turbo_method": :delete, "turbo-confirm": "Are you sure?"}, class: "btn btn-outline-danger" %>
		</div>

	</div>

	<!-- Quotes -->

	<div class="ms-3">
		<h3>Quotes</h3>
	</div>
	<% if @client.quotes.empty? %>
		<div class="ms-3"> No quotes available </div>
	<% end %>
		
	
	<% @client.quotes.each do |quote|  %>
		<div class="m-3">
			<div>
				Quote Type: <%= quote.quote_type.humanize  %>
			</div>
			<div>
				Quote Amount: <%= number_to_currency(quote.amount, precision: 0) %>
			</div>
			<div>
				<%= link_to "View PDF", quote_pdf_path(quote) %>
			</div>
			<div >
				<%= link_to "Email quote to client", quote_path(quote) + "/send_quote"%>
			</div>
		</div>
	<% end %>
</div>