config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/clients'
    get 'admin/users'
    get 'users/profile'
    get 'acc/:id/edit', to: 'admin_company_contacts#edit', as: "edit_acc"
    patch 'acc/:id', to: 'admin_company_contacts#update'
  end

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'u/:id', to: 'users#profile', as: 'user'
  delete "u/:id", to: 'users#destroy'
  get '/user' => "clients#index", :as => :user_root

  #created to filter clients in the table
  resources :clients do
    collection do
      get 'list'
    end
  end

  #send emails to clients
  get 'clients/:id/send_welcome', to: 'clients#welcome'
  get 'quotes/:id/send_quote', to: 'quotes#send_quote'

  #pages roots with quotes
  root 'pages#index'
  get '/stats', to: 'pages#stats'
  get 'quote', to: "pages#quote"
  get 'download', to: "pages#download"
  get 'preview', to: "pages#preview"
  get 'quote/pdf/:id', to: "quotes#pdf", as: 'quote_pdf'

end

app/views/pages/index.html.erb
<%= render 'devise/shared/error_messages', resource: resource %>

<div class="container col-6 mt-5">
	<div class="card text-center border-dark">
		<h1 class="card-header border-dark">SpaceByn CRM</h1>

		<div class="card-body">
			<h2 class="card-title">Login</h2>

			<%= form_for(resource, as: resource_name, url: session_path(resource_name), data: {turbo: false}) do |f| %>

			  <div class="field">
			    <%= f.label :email %><br />
			    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
			  </div>

			  <div class="field">
			    <%= f.label :password %><br />
			    <%= f.password_field :password, autocomplete: "current-password" %>
			  </div>

			  <% if devise_mapping.rememberable? %>
			    <div class="field">
			      <%= f.check_box :remember_me %>
			      <%= f.label :remember_me %>
			    </div>
			  <% end %>

			  <div class="actions">
			    <%= f.submit "Login", class: "btn btn-primary"%>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/pages/quote.html.erb
<h2>This is the quote generation page</h2>

<%= link_to "Download this page", download_path %>
<%= link_to "Preview this page", preview_path %>
<%= link_to "New Quote", new_quote_path %>

app/views/pages/stats.html.erb
<div class="container">
	<h1>Stats Page</h1>

	<p>Number of clients: <%= @clients.count %></p>
	<p>Number of quotes: <%= @quotes.count %>
</div>